[package]
name = "zebot2"
version = "0.1.0"
edition = "2021"
authors = [ "Marcus Borkenhagen <m AT fritschy DOT de>" ]

[dependencies]
irc2 = { git = "https://github.com/fritschy/zebot.git", package = "irc2" }
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0.14", features = ["derive"] }

tokio-rustls = { version = "0.23.2", optional = true }
webpki-roots = { version = "0.22.2", optional = true }

tokio-native-tls = { version = "0.3.0", optional = true }

[features]
default = ["tokio-rustls", "webpki-roots"]
native-tls = ["tokio-native-tls"]

[profile.release]
lto = true
