#!/usr/bin/env python3

from handler_lib import handler_exit, get_args

import socket
import json

try:
    c=socket.create_connection(('10.0.0.126', 8001))
except:
    handler_exit(1, error="Could not connect to ask service")

try:
    c.send(get_args().encode())
except:
    handler_exit(1, error="Could not communicate to ask service")

try:
    r=c.recv(8192)
except:
    handler_exit(1, error="Could not receive response")

j=json.loads(r.decode())
lines = [j['choices'][x]['message']['content'].strip() for x in range(len(j['choices']))]
handler_exit(0, lines=lines, box=1, wrap_single_lines=1, title=j['model'])

# vim:set ft=python:
