#!/usr/bin/env python3

from handler_lib import handler_exit, get_split_args, get_from
import errno
import os

args = get_split_args()
if args[0].upper().startswith('E'):
    i = getattr(errno, args[0].upper())
else:
    i = int(args[0])
handler_exit(0, lines=["{}: errno {}, {}: {}".format(get_from(), i, errno.errorcode[i], os.strerror(i))])
