#!/usr/bin/env python3

from mechanize import Browser
from bs4 import BeautifulSoup
from random import choice
from handler_lib import handler_exit

jj = ['Jokes', 'Unclejokes', 'dadjokes']
j = choice(jj)

br = Browser()
br.set_handle_robots(False)
br.addheaders=[('User-Agent', 'Mozilla/6.0 (X11; U; Linux; 3.2.0)')]
url = 'https://old.reddit.com/r/{}/random'.format(j)
r = br.open(url)
url = r.geturl().split('?')[0]
d = r.get_data()
bs = BeautifulSoup(d, features='lxml')
title = bs.find('a', attrs={'class': 'title'})
text = bs.find('div', attrs={'class': 'expando'})

lines = [title.text, *list(filter(lambda x: len(x) > 0, map(str.strip, text.text.splitlines())))]
handler_exit(0, lines=lines, box=1, wrap_single_lines=1, title='r/{}'.format(j), link=url)

# vim:set ft=python:
