#!/usr/bin/env python3

from handler_lib import handler_exit, get_split_args, get_from
import signal

args = get_split_args()

if args[0].upper().startswith('SIG') and not args[0].upper().startswith('SIG_'):
    i = getattr(signal, args[0].upper())
else:
    i = int(args[0])

signals = dict(map(lambda x: (x, getattr(signal, x).value), filter(lambda x: x.startswith('SIG'), dir(signal))))
names = dict(map(lambda x: (x[1], x[0]), signals.items()))
handler_exit(0, lines=[
    "{}: signal {}, {}".format(
        get_from(),
        names.get(i, None),
        i,
    )])
