#!/usr/bin/env python3

from handler_lib import *
from urllib.request import urlopen, quote as urlquote
from bs4 import BeautifulSoup as BS

args = urlquote(get_args())
url = "https://www.urbandictionary.com/define.php?term={}".format(args)
with urlopen(url) as r:
    bs=BS(r.read(), features="lxml")

try:
    title = bs.find("h1", attrs={"class": "flex-1"}).text.strip()
except:
    try:
        title = bs.find("a", attrs={"class": "text-denim"}).text.strip()
    except:
        title = args

lines = []
numbered = False
for line in bs.find("div", attrs={"class": "meaning"}).stripped_strings:
    # some definitions have numbered variants in one #meaning
    if re.match(r'^\d\.', line):
        lines.append(line)
        numbered = True
    else:
        if len(lines) == 0:
            lines.append(line)
        else:
            lines[-1] += " " + line

if numbered:
    handler_exit(0, lines=lines, link=url, title=title, box=1, wrap_single_lines=1)
else:
    handler_exit(0, lines=lines, link=url, title=title, box=1, wrap=1)
