#!/usr/bin/env python3

from handler_lib import handler_exit, get_args, get_from, get_to
import re

args = get_args()
nick = get_from()
channel = get_to()

with open("rw_data/urls.txt") as f:
    # handler_exit(1, error={'args': args, 'nick': nick, 'channel': channel, 'msg': list(filter(lambda x: x[1] == channel, map(lambda x: x.strip().split("\t"), f.readlines())))})
    if len(args) < 1:
        lines = list(filter(lambda x: x[1] == channel, map(lambda x: x.strip().split("\t", 3), f.readlines())))
        if len(lines) > 0:
            time, chan, nick, url = lines[-1]
            handler_exit(0, lines=["Last URL from {}: {}".format(nick, url)])
        else:
            pass
    else:
        for i in (args, ".*{}.*".format(args)):
            lines = list(filter(lambda x: x[1] == channel and re.search(i, x[3]) is not None, map(lambda x: x.strip().split("\t", 3), f.readlines())))
            if len(lines) > 0:
                break
        if len(lines) > 4:
            lines = lines[-4:]
        lines = list(map(lambda x: x[3], lines))
        handler_exit(0, lines=lines)